import { Injectable } from '@angular/core';
import { User } from '../interfaces/user';
import { FIUser } from './../interfaces/fiUser';

@Injectable({
  providedIn: 'root'
})
export class UserService {

  constructor() { }
 makers: User[] = [
   {
     "id": 1,
     "firstname": "Sefakor",
     "lastname": "Agbloyor",
     "phoneNumber": "24445617",
     "email": "Agbloyor1Sefakor@gmail.com",
     "role": "checker",
     "createdBy": "Super Admin",
     "createdDate": "2023-09-12T02:09:22.672Z",
     "password": "jsIMxlHbZy",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 2,
     "firstname": "Daniel",
     "lastname": "Daniels",
     "phoneNumber": "24445627",
     "email": "Daniels2Daniel@gmail.com",
     "role": "checker",
     "createdBy": "Super Admin",
     "createdDate": "2023-08-08T16:17:23.271Z",
     "password": "lfhuBiDAda",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 3,
     "firstname": "Samaria",
     "lastname": "Dagadu",
     "phoneNumber": "24445637",
     "email": "Dagadu3Samaria@gmail.com",
     "role": "checker",
     "createdBy": "Super Admin",
     "createdDate": "2023-03-24T07:12:47.859Z",
     "password": "PtmAciAycD",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 4,
     "firstname": "Daniel",
     "lastname": "Nuamah",
     "phoneNumber": "24445647",
     "email": "Nuamah4Daniel@gmail.com",
     "role": "checker",
     "createdBy": "Super Admin",
     "createdDate": "2023-03-19T23:51:48.541Z",
     "password": "WgDAVfqwNQ",
     "remember": true,
     "status": "New"
   },
   {
     "id": 5,
     "firstname": "David",
     "lastname": "Anane",
     "phoneNumber": "24445657",
     "email": "Anane5David@gmail.com",
     "role": "checker",
     "createdBy": "Super Admin",
     "createdDate": "2023-03-13T02:26:11.115Z",
     "password": "coxQUGrOMM",
     "remember": true,
     "status": "New"
   },
   {
     "id": 6,
     "firstname": "Daniel",
     "lastname": "Osei",
     "phoneNumber": "24445667",
     "email": "Osei6Daniel@gmail.com",
     "role": "checker",
     "createdBy": "Super Admin",
     "createdDate": "2023-01-24T15:21:22.868Z",
     "password": "yBXSUhnbEB",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 7,
     "firstname": "Agatha",
     "lastname": "Daniels",
     "phoneNumber": "24445677",
     "email": "Daniels7Agatha@gmail.com",
     "role": "checker",
     "createdBy": "Super Admin",
     "createdDate": "2023-06-29T23:01:02.108Z",
     "password": "QIvqgkXwvf",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 8,
     "firstname": "Lois",
     "lastname": "Osei",
     "phoneNumber": "24445687",
     "email": "Osei8Lois@gmail.com",
     "role": "checker",
     "createdBy": "Super Admin",
     "createdDate": "2023-09-13T15:56:41.785Z",
     "password": "fFjzqoTpol",
     "remember": true,
     "status": "New"
   },
   {
     "id": 9,
     "firstname": "Sefakor",
     "lastname": "Donkor",
     "phoneNumber": "24445697",
     "email": "Donkor9Sefakor@gmail.com",
     "role": "checker",
     "createdBy": "Super Admin",
     "createdDate": "2023-02-13T01:33:50.481Z",
     "password": "WiSyihZZAH",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 10,
     "firstname": "Agatha",
     "lastname": "Gyamfi",
     "phoneNumber": "244456107",
     "email": "Gyamfi10Agatha@gmail.com",
     "role": "checker",
     "createdBy": "Super Admin",
     "createdDate": "2023-05-03T23:47:20.772Z",
     "password": "WErcoumrFc",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 11,
     "firstname": "Samaria",
     "lastname": "Osei",
     "phoneNumber": "244456117",
     "email": "Osei11Samaria@gmail.com",
     "role": "checker",
     "createdBy": "Super Admin",
     "createdDate": "2023-04-16T07:49:47.339Z",
     "password": "uCMZqnDNFg",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 12,
     "firstname": "Sefakor",
     "lastname": "Obeng",
     "phoneNumber": "244456127",
     "email": "Obeng12Sefakor@gmail.com",
     "role": "checker",
     "createdBy": "Super Admin",
     "createdDate": "2023-03-08T09:34:04.793Z",
     "password": "AFrQuFVgun",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 13,
     "firstname": "Agatha",
     "lastname": "Dagadu",
     "phoneNumber": "244456137",
     "email": "Dagadu13Agatha@gmail.com",
     "role": "checker",
     "createdBy": "Super Admin",
     "createdDate": "2023-05-11T22:29:14.202Z",
     "password": "wjNVLtckeI",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 14,
     "firstname": "Agatha",
     "lastname": "Donkor",
     "phoneNumber": "244456147",
     "email": "Donkor14Agatha@gmail.com",
     "role": "checker",
     "createdBy": "Super Admin",
     "createdDate": "2023-06-01T14:25:04.512Z",
     "password": "CJJPnZKltD",
     "remember": true,
     "status": "New"
   },
   {
     "id": 15,
     "firstname": "Lois",
     "lastname": "Daniels",
     "phoneNumber": "244456157",
     "email": "Daniels15Lois@gmail.com",
     "role": "checker",
     "createdBy": "Super Admin",
     "createdDate": "2023-01-05T16:06:52.593Z",
     "password": "KHmvkbYlBY",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 16,
     "firstname": "David",
     "lastname": "Daniels",
     "phoneNumber": "244456167",
     "email": "Daniels16David@gmail.com",
     "role": "checker",
     "createdBy": "Super Admin",
     "createdDate": "2023-08-24T14:22:45.538Z",
     "password": "uUACVfdncF",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 17,
     "firstname": "Samaria",
     "lastname": "Vanderpuije",
     "phoneNumber": "244456177",
     "email": "Vanderpuije17Samaria@gmail.com",
     "role": "checker",
     "createdBy": "Super Admin",
     "createdDate": "2023-06-20T11:46:31.940Z",
     "password": "MNISIFDMcu",
     "remember": true,
     "status": "New"
   },
   {
     "id": 18,
     "firstname": "Richeal",
     "lastname": "Daniels",
     "phoneNumber": "244456187",
     "email": "Daniels18Richeal@gmail.com",
     "role": "checker",
     "createdBy": "Super Admin",
     "createdDate": "2023-06-23T19:25:41.565Z",
     "password": "URhjPAYPoW",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 19,
     "firstname": "Joseph",
     "lastname": "Anane",
     "phoneNumber": "244456197",
     "email": "Anane19Joseph@gmail.com",
     "role": "checker",
     "createdBy": "Super Admin",
     "createdDate": "2023-04-03T18:38:42.756Z",
     "password": "IPJGsTXNiM",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 20,
     "firstname": "Richeal",
     "lastname": "Donkor",
     "phoneNumber": "244456207",
     "email": "Donkor20Richeal@gmail.com",
     "role": "checker",
     "createdBy": "Super Admin",
     "createdDate": "2023-08-05T11:00:36.963Z",
     "password": "rMEXhDBJWi",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 21,
     "firstname": "Richeal",
     "lastname": "Tetteh",
     "phoneNumber": "244456217",
     "email": "Tetteh21Richeal@gmail.com",
     "role": "checker",
     "createdBy": "Super Admin",
     "createdDate": "2023-05-19T06:04:24.236Z",
     "password": "WXvgAxWDeX",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 22,
     "firstname": "Sefakor",
     "lastname": "Agyeman",
     "phoneNumber": "244456227",
     "email": "Agyeman22Sefakor@gmail.com",
     "role": "checker",
     "createdBy": "Super Admin",
     "createdDate": "2023-03-25T02:24:28.534Z",
     "password": "OjxTCNvBEF",
     "remember": true,
     "status": "New"
   },
   {
     "id": 23,
     "firstname": "Daniel",
     "lastname": "Vanderpuije",
     "phoneNumber": "244456237",
     "email": "Vanderpuije23Daniel@gmail.com",
     "role": "checker",
     "createdBy": "Super Admin",
     "createdDate": "2023-04-05T17:28:29.678Z",
     "password": "zAZTypQLsQ",
     "remember": true,
     "status": "New"
   }
 ]


checkers: User[] = [
  {
    "id": 1,
    "firstname": "Israel",
    "lastname": "Tetteh",
    "phoneNumber": "24445617",
    "email": "Tetteh1Israel@gmail.com",
    "role": "checker",
    "createdBy": "Super Admin",
    "createdDate": "2023-05-14T03:26:02.666Z",
    "password": "SwixgDczgd",
    "remember": true,
    "status": "Active"
  },
  {
    "id": 2,
    "firstname": "Samaria",
    "lastname": "Daniels",
    "phoneNumber": "24445627",
    "email": "Daniels2Samaria@gmail.com",
    "role": "checker",
    "createdBy": "Super Admin",
    "createdDate": "2023-07-22T17:10:53.987Z",
    "password": "vSufWFcCWB",
    "remember": true,
    "status": "New"
  },
  {
    "id": 3,
    "firstname": "Prince",
    "lastname": "Ofosu",
    "phoneNumber": "24445637",
    "email": "Ofosu3Prince@gmail.com",
    "role": "checker",
    "createdBy": "Super Admin",
    "createdDate": "2023-04-20T01:07:34.991Z",
    "password": "OvPlIbQKtA",
    "remember": true,
    "status": "New"
  },
  {
    "id": 4,
    "firstname": "David",
    "lastname": "Nyarko",
    "phoneNumber": "24445647",
    "email": "Nyarko4David@gmail.com",
    "role": "checker",
    "createdBy": "Super Admin",
    "createdDate": "2023-09-10T09:22:42.345Z",
    "password": "OuNBjDyquB",
    "remember": true,
    "status": "Active"
  },
  {
    "id": 5,
    "firstname": "Joseph",
    "lastname": "Daniels",
    "phoneNumber": "24445657",
    "email": "Daniels5Joseph@gmail.com",
    "role": "checker",
    "createdBy": "Super Admin",
    "createdDate": "2023-03-27T20:57:18.187Z",
    "password": "HQOTmbjuIt",
    "remember": true,
    "status": "Blocked"
  },
  {
    "id": 6,
    "firstname": "Richeal",
    "lastname": "Ofosu",
    "phoneNumber": "24445667",
    "email": "Ofosu6Richeal@gmail.com",
    "role": "checker",
    "createdBy": "Super Admin",
    "createdDate": "2023-05-03T11:33:50.724Z",
    "password": "AJAhbzIsQT",
    "remember": true,
    "status": "Blocked"
  },
  {
    "id": 7,
    "firstname": "Joseph",
    "lastname": "Vanderpuije",
    "phoneNumber": "24445677",
    "email": "Vanderpuije7Joseph@gmail.com",
    "role": "checker",
    "createdBy": "Super Admin",
    "createdDate": "2023-05-17T20:14:11.858Z",
    "password": "eCKBkUlIJo",
    "remember": true,
    "status": "Active"
  },
  {
    "id": 8,
    "firstname": "Lois",
    "lastname": "Dankyi",
    "phoneNumber": "24445687",
    "email": "Dankyi8Lois@gmail.com",
    "role": "checker",
    "createdBy": "Super Admin",
    "createdDate": "2023-04-24T02:10:51.540Z",
    "password": "jmLpMBZywQ",
    "remember": true,
    "status": "Blocked"
  },
  {
    "id": 9,
    "firstname": "Lois",
    "lastname": "Tetteh",
    "phoneNumber": "24445697",
    "email": "Tetteh9Lois@gmail.com",
    "role": "checker",
    "createdBy": "Super Admin",
    "createdDate": "2023-06-14T00:09:40.386Z",
    "password": "HInbynAVyL",
    "remember": true,
    "status": "Blocked"
  },
  {
    "id": 10,
    "firstname": "Samaria",
    "lastname": "Gyamfi",
    "phoneNumber": "244456107",
    "email": "Gyamfi10Samaria@gmail.com",
    "role": "checker",
    "createdBy": "Super Admin",
    "createdDate": "2023-01-03T16:04:16.411Z",
    "password": "FgxohIZYsF",
    "remember": true,
    "status": "Active"
  },
  {
    "id": 11,
    "firstname": "Lois",
    "lastname": "Daniels",
    "phoneNumber": "244456117",
    "email": "Daniels11Lois@gmail.com",
    "role": "checker",
    "createdBy": "Super Admin",
    "createdDate": "2023-06-05T04:39:02.296Z",
    "password": "ulADRmeOFe",
    "remember": true,
    "status": "New"
  },
  {
    "id": 12,
    "firstname": "Samaria",
    "lastname": "Obeng",
    "phoneNumber": "244456127",
    "email": "Obeng12Samaria@gmail.com",
    "role": "checker",
    "createdBy": "Super Admin",
    "createdDate": "2023-01-12T21:21:45.370Z",
    "password": "YXLEiyVzOo",
    "remember": true,
    "status": "Active"
  },
  {
    "id": 13,
    "firstname": "Richeal",
    "lastname": "Tetteh",
    "phoneNumber": "244456137",
    "email": "Tetteh13Richeal@gmail.com",
    "role": "checker",
    "createdBy": "Super Admin",
    "createdDate": "2023-05-22T16:19:08.826Z",
    "password": "eYcxLMIFvt",
    "remember": true,
    "status": "Blocked"
  },
  {
    "id": 14,
    "firstname": "David",
    "lastname": "Amorin",
    "phoneNumber": "244456147",
    "email": "Amorin14David@gmail.com",
    "role": "checker",
    "createdBy": "Super Admin",
    "createdDate": "2023-04-08T13:00:20.904Z",
    "password": "JzKEMXAxwv",
    "remember": true,
    "status": "Active"
  },
  {
    "id": 15,
    "firstname": "Joseph",
    "lastname": "Gyamfi",
    "phoneNumber": "244456157",
    "email": "Gyamfi15Joseph@gmail.com",
    "role": "checker",
    "createdBy": "Super Admin",
    "createdDate": "2023-09-20T05:36:14.800Z",
    "password": "UVFPEmsyof",
    "remember": true,
    "status": "Active"
  },
  {
    "id": 16,
    "firstname": "Sam",
    "lastname": "Ofosu",
    "phoneNumber": "244456167",
    "email": "Ofosu16Sam@gmail.com",
    "role": "checker",
    "createdBy": "Super Admin",
    "createdDate": "2023-04-29T21:22:56.143Z",
    "password": "mBTNGvJrdo",
    "remember": true,
    "status": "Active"
  },
  {
    "id": 17,
    "firstname": "Rita",
    "lastname": "Vanderpuije",
    "phoneNumber": "244456177",
    "email": "Vanderpuije17Rita@gmail.com",
    "role": "checker",
    "createdBy": "Super Admin",
    "createdDate": "2023-06-22T21:30:23.189Z",
    "password": "yjEjYnCVpP",
    "remember": true,
    "status": "Blocked"
  },
  {
    "id": 18,
    "firstname": "Samaria",
    "lastname": "Bonsu",
    "phoneNumber": "244456187",
    "email": "Bonsu18Samaria@gmail.com",
    "role": "checker",
    "createdBy": "Super Admin",
    "createdDate": "2023-01-13T13:36:37.304Z",
    "password": "TTyhzDFPBL",
    "remember": true,
    "status": "Active"
  },
  {
    "id": 19,
    "firstname": "Joel",
    "lastname": "Bonsu",
    "phoneNumber": "244456197",
    "email": "Bonsu19Joel@gmail.com",
    "role": "checker",
    "createdBy": "Super Admin",
    "createdDate": "2023-04-01T20:35:12.851Z",
    "password": "LzTjBtazAl",
    "remember": true,
    "status": "Active"
  },
  {
    "id": 20,
"firstname": "Joseph",
    "lastname": "Daniels",
    "phoneNumber": "244456207",
    "email": "Daniels20Joseph@gmail.com",
    "role": "checker",
    "createdBy": "Super Admin",
    "createdDate": "2023-07-06T18:28:09.354Z",
    "password": "VLHUDGkNNC",
    "remember": true,
    "status": "Active"
  },
  {
    "id": 21,
    "firstname": "Joel",
    "lastname": "Tetteh",
    "phoneNumber": "244456217",
    "email": "Tetteh21Joel@gmail.com",
    "role": "checker",
    "createdBy": "Super Admin",
    "createdDate": "2023-08-26T21:07:26.913Z",
    "password": "JnzInOWkiA",
    "remember": true,
    "status": "Active"
  },
  {
    "id": 22,
    "firstname": "Vincent",
    "lastname": "Vanderpuije",
    "phoneNumber": "244456227",
    "email": "Vanderpuije22Vincent@gmail.com",
    "role": "checker",
    "createdBy": "Super Admin",
    "createdDate": "2023-04-20T18:14:53.396Z",
    "password": "jDtkuTRmaW",
    "remember": true,
    "status": "Active"
  },
  {
    "id": 23,
    "firstname": "Alex",
    "lastname": "Peprah",
    "phoneNumber": "244456237",
    "email": "Peprah23Alex@gmail.com",
    "role": "checker",
    "createdBy": "Super Admin",
    "createdDate": "2023-07-10T05:55:25.292Z",
    "password": "TgHWSdyFCV",
    "remember": true,
    "status": "Blocked"
  }
]


banks: FIUser[] =
[
  {
    "id": 1,
    "fi_name": "National Bank",
    "fi_shortName": "NB1",
    "fi_code": "FI014831",
    "fi_type": "Bank",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.792Z",
    "password": "ytiWXdWhwr",
    "status": "Deleted"
  },
  {
    "id": 2,
    "fi_name": "United Bank",
    "fi_shortName": "UB2",
    "fi_code": "FI014832",
    "fi_type": "Bank",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.792Z",
    "password": "gfkWshxcCV",
    "status": "Active"
  },
  {
    "id": 3,
    "fi_name": "Commercial Microfinance",
    "fi_shortName": "CM3",
    "fi_code": "FI014833",
    "fi_type": "Non-Bank Financial",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.792Z",
    "password": "CEJJlXdfoT",
    "status": "Deleted"
  },
  {
    "id": 4,
    "fi_name": "Agricultural Savings & Loans",
    "fi_shortName": "AS4",
    "fi_code": "FI014834",
    "fi_type": "Non-Bank Financial",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.792Z",
    "password": "msMEzAafJo",
    "status": "Deactivated"
  },
  {
    "id": 5,
    "fi_name": "National Bank",
    "fi_shortName": "NB5",
    "fi_code": "FI014835",
    "fi_type": "Bank",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.792Z",
    "password": "TbKFkTQynV",
    "status": "Active"
  },
  {
    "id": 6,
    "fi_name": "Agricultural Bank",
    "fi_shortName": "AB6",
    "fi_code": "FI014836",
    "fi_type": "Bank",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.792Z",
    "password": "LcxDOpzkEo",
    "status": "Active"
  },
  {
    "id": 7,
    "fi_name": "Development Bank",
    "fi_shortName": "DB7",
    "fi_code": "FI014837",
    "fi_type": "Bank",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.792Z",
    "password": "IfauHIUDYx",
    "status": "Deactivated"
  },
  {
    "id": 8,
    "fi_name": "National Bank",
    "fi_shortName": "NB8",
    "fi_code": "FI014838",
    "fi_type": "Bank",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.792Z",
    "password": "oULOQQeMmt",
    "status": "Active"
  },
  {
    "id": 9,
    "fi_name": "Commercial Bank",
    "fi_shortName": "CB9",
    "fi_code": "FI014839",
    "fi_type": "Bank",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.792Z",
    "password": "DXgtGvHcME",
    "status": "Deactivated"
  },
  {
    "id": 10,
    "fi_name": "United Bank",
    "fi_shortName": "UB10",
    "fi_code": "FI0148310",
    "fi_type": "Bank",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.792Z",
    "password": "YGByMXvKZC",
    "status": "Deactivated"
  },
  {
    "id": 11,
    "fi_name": "National Bank",
    "fi_shortName": "NB11",
    "fi_code": "FI0148311",
    "fi_type": "Bank",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.793Z",
    "password": "TjVQqHoixU",
    "status": "Deleted"
  },
  {
    "id": 12,
    "fi_name": "Capital Microfinance",
    "fi_shortName": "CM12",
    "fi_code": "FI0148312",
    "fi_type": "Non-Bank Financial",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.793Z",
    "password": "yMClhRDLgP",
    "status": "Active"
  },
  {
    "id": 13,
    "fi_name": "Commercial Savings & Loans",
    "fi_shortName": "CS13",
    "fi_code": "FI0148313",
    "fi_type": "Non-Bank Financial",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.793Z",
    "password": "NaKoWHNCjh",
    "status": "Active"
  },
  {
    "id": 14,
    "fi_name": "Agricultural Bank",
    "fi_shortName": "AB14",
    "fi_code": "FI0148314",
    "fi_type": "Bank",
   "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.793Z",
    "password": "FunJLyPEcE",
    "status": "Active"
  },
  {
    "id": 15,
    "fi_name": "United Microfinance",
    "fi_shortName": "UM15",
    "fi_code": "FI0148315",
    "fi_type": "Non-Bank Financial",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.793Z",
    "password": "TNEJygQTPC",
    "status": "Active"
  }
]


}
