import { Injectable } from '@angular/core';
import { User } from '../interfaces/user';

@Injectable({
  providedIn: 'root'
})
export class UserService {

  constructor() { }
 newUsers: User[] = [
   {
     "id": 1,
     "firstname": "Lois",
     "lastname": "Obeng",
     "phoneNumber": "024445617",
     "email": "Obeng1Lois@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "glynazlTwc",
     "remember": true,
     "status": "Locked"
   },
   {
     "id": 2,
     "firstname": "Emma",
     "lastname": "Vanderpuije",
     "phoneNumber": "024445627",
     "email": "Vanderpuije2Emma@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "qjWlCeqYVN",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 3,
     "firstname": "Alex",
     "lastname": "Amorin",
     "phoneNumber": "024445637",
     "email": "Amorin3Alex@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "BCzkUqlKvu",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 4,
     "firstname": "Emma",
     "lastname": "Badu",
     "phoneNumber": "024445647",
     "email": "Badu4Emma@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "NrMQLoNVxW",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 5,
     "firstname": "Yaa",
     "lastname": "Ofosu",
     "phoneNumber": "024445657",
     "email": "Ofosu5Yaa@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "QyNMmteTCN",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 6,
     "firstname": "Lois",
     "lastname": "Tetteh",
     "phoneNumber": "024445667",
     "email": "Tetteh6Lois@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "pEyojLRQrh",
     "remember": true,
     "status": "Verified"
   },
   {
     "id": 7,
     "firstname": "Joel",
     "lastname": "Ofosu",
     "phoneNumber": "024445677",
     "email": "Ofosu7Joel@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "CdDAfaRrFx",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 8,
     "firstname": "Joel",
     "lastname": "Ofosu",
     "phoneNumber": "024445687",
     "email": "Ofosu8Joel@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "bQKuSObixC",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 9,
     "firstname": "David",
     "lastname": "Daniels",
     "phoneNumber": "024445697",
     "email": "Daniels9David@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "LhxfFdRQas",
     "remember": true,
     "status": "Locked"
   },
   {
     "id": 10,
     "firstname": "Samaria",
     "lastname": "Dankyi",
     "phoneNumber": "0244456107",
     "email": "Dankyi10Samaria@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "mSFKteAttY",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 11,
     "firstname": "Agatha",
     "lastname": "Daniels",
     "phoneNumber": "0244456117",
     "email": "Daniels11Agatha@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "OFGrhjaOlB",
     "remember": true,
     "status": "Verified"
   },
   {
     "id": 12,
     "firstname": "Emma",
     "lastname": "Agyeman",
     "phoneNumber": "0244456127",
     "email": "Agyeman12Emma@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
 "password": "KeuWbsekKi",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 13,
     "firstname": "Richeal",
     "lastname": "Vanderpuije",
     "phoneNumber": "0244456137",
     "email": "Vanderpuije13Richeal@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "OYXKvtEvHV",
     "remember": true,
     "status": "Verified"
   },
   {
     "id": 14,
     "firstname": "Joseph",
     "lastname": "Daniels",
     "phoneNumber": "0244456147",
     "email": "Daniels14Joseph@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "gNnYFUNHZB",
     "remember": true,
     "status": "Verified"
   },
   {
     "id": 15,
     "firstname": "Vincent",
     "lastname": "Obeng",
     "phoneNumber": "0244456157",
     "email": "Obeng15Vincent@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "LnJtymKMKV",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 16,
     "firstname": "Samaria",
     "lastname": "Osei",
     "phoneNumber": "0244456167",
     "email": "Osei16Samaria@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "xfRhNeuHlr",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 17,
     "firstname": "Samaria",
     "lastname": "Nyarko",
     "phoneNumber": "0244456177",
     "email": "Nyarko17Samaria@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "fSYsSrACTc",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 18,
     "firstname": "Felix",
     "lastname": "Daniels",
     "phoneNumber": "0244456187",
     "email": "Daniels18Felix@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "MmBJfYNHFK",
     "remember": true,
     "status": "Locked"
   },
   {
     "id": 19,
     "firstname": "Vincent",
     "lastname": "Nuamah",
     "phoneNumber": "0244456197",
     "email": "Nuamah19Vincent@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "ZUmyJnmuct",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 20,
     "firstname": "Vincent",
     "lastname": "Nyarko",
     "phoneNumber": "0244456207",
     "email": "Nyarko20Vincent@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "lMegiKWbYZ",
     "remember": true,
     "status": "Verified"
   },
   {
     "id": 21,
     "firstname": "Richeal",
     "lastname": "Nyarko",
     "phoneNumber": "0244456217",
     "email": "Nyarko21Richeal@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "BMRdycfsLf",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 22,
     "firstname": "Sefakor",
     "lastname": "Gyamfi",
     "phoneNumber": "0244456227",
     "email": "Gyamfi22Sefakor@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "eWzFHxcHWf",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 23,
     "firstname": "Rita",
     "lastname": "Tetteh",
     "phoneNumber": "0244456237",
     "email": "Tetteh23Rita@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "yrMtLZiiHJ",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 24,
     "firstname": "Alex",
     "lastname": "Nuamah",
     "phoneNumber": "0244456247",
     "email": "Nuamah24Alex@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "CPVHyGYmbj",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 25,
     "firstname": "Yaa",
     "lastname": "Amorin",
     "phoneNumber": "0244456257",
     "email": "Amorin25Yaa@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "AEmiyXttMg",
     "remember": true,
     "status": "Locked"
   },
   {
     "id": 26,
     "firstname": "Rita",
     "lastname": "Obeng",
     "phoneNumber": "0244456267",
     "email": "Obeng26Rita@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "tegqQBzMRp",
     "remember": true,
     "status": "Verified"
   },
   {
     "id": 27,
     "firstname": "Vincent",
     "lastname": "Peprah",
     "phoneNumber": "0244456277",
     "email": "Peprah27Vincent@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "TVsJqqqbxE",
     "remember": true,
     "status": "Verified"
   },
   {
     "id": 28,
     "firstname": "Alex",
     "lastname": "Badu",
     "phoneNumber": "0244456287",
     "email": "Badu28Alex@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "qTcGdcAPfl",
     "remember": true,
     "status": "Verified"
   },
   {
     "id": 29,
     "firstname": "Yaa",
     "lastname": "Vanderpuije",
     "phoneNumber": "0244456297",
     "email": "Vanderpuije29Yaa@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "lzXCkDjlRs",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 30,
     "firstname": "Agatha",
     "lastname": "Vanderpuije",
     "phoneNumber": "0244456307",
     "email": "Vanderpuije30Agatha@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "XXTHSTSdbz",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 31,
     "firstname": "Sefakor",
     "lastname": "Nuamah",
     "phoneNumber": "0244456317",
     "email": "Nuamah31Sefakor@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "zMGPpqJnVs",
     "remember": true,
     "status": "Verified"
   },
   {
     "id": 32,
     "firstname": "Felix",
     "lastname": "Gyamfi",
     "phoneNumber": "0244456327",
     "email": "Gyamfi32Felix@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "CNFzmdygQL",
     "remember": true,
     "status": "Verified"
   },
   {
     "id": 33,
     "firstname": "Agatha",
     "lastname": "Gyamfi",
     "phoneNumber": "0244456337",
     "email": "Gyamfi33Agatha@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "gHrYGorMzp",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 34,
     "firstname": "Prince",
     "lastname": "Bonsu",
     "phoneNumber": "0244456347",
     "email": "Bonsu34Prince@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "zALhysODdb",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 35,
     "firstname": "Felix",
     "lastname": "Obeng",
     "phoneNumber": "0244456357",
     "email": "Obeng35Felix@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "hSNuXeDTNB",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 36,
     "firstname": "Rita",
     "lastname": "Osei",
     "phoneNumber": "0244456367",
     "email": "Osei36Rita@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "bVZzhQBZcu",
     "remember": true,
     "status": "Locked"
   },
   {
     "id": 37,
     "firstname": "Sam",
     "lastname": "Nyarko",
     "phoneNumber": "0244456377",
     "email": "Nyarko37Sam@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "CrXHogsTXa",
     "remember": true,
     "status": "Locked"
   },
   {
     "id": 38,
     "firstname": "Sam",
     "lastname": "Daniels",
     "phoneNumber": "0244456387",
     "email": "Daniels38Sam@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "OhNxEzIJXb",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 39,
     "firstname": "Richeal",
     "lastname": "Daniels",
     "phoneNumber": "0244456397",
     "email": "Daniels39Richeal@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "Yqixdxqglh",
     "remember": true,
     "status": "Locked"
   },
   {
     "id": 40,
     "firstname": "Sam",
     "lastname": "Peprah",
     "phoneNumber": "0244456407",
     "email": "Peprah40Sam@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "FwXmpVwEGC",
     "remember": true,
     "status": "Locked"
   },
   {
     "id": 41,
     "firstname": "Yaa",
     "lastname": "Tetteh",
     "phoneNumber": "0244456417",
     "email": "Tetteh41Yaa@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "iQjQXquUhb",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 42,
     "firstname": "Sam",
     "lastname": "Badu",
     "phoneNumber": "0244456427",
     "email": "Badu42Sam@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "IIXtTKDhjf",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 43,
     "firstname": "Joseph",
     "lastname": "Vanderpuije",
     "phoneNumber": "0244456437",
     "email": "Vanderpuije43Joseph@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "PBeecBRJrm",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 44,
     "firstname": "Yaa",
     "lastname": "Ofosu",
     "phoneNumber": "0244456447",
     "email": "Ofosu44Yaa@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "qwNcBrnsCu",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 45,
     "firstname": "Prince",
     "lastname": "Daniels",
     "phoneNumber": "0244456457",
     "email": "Daniels45Prince@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "IAVbvWBceT",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 46,
     "firstname": "Prince",
     "lastname": "Badu",
     "phoneNumber": "0244456467",
     "email": "Badu46Prince@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "HjnYFjHBii",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 47,
     "firstname": "Yaa",
     "lastname": "Ofosu",
     "phoneNumber": "0244456477",
     "email": "Ofosu47Yaa@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "xBybOkiAhH",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 48,
     "firstname": "Joel",
     "lastname": "Gyamfi",
     "phoneNumber": "0244456487",
     "email": "Gyamfi48Joel@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "OYBiWMbKuL",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 49,
     "firstname": "Vincent",
     "lastname": "Nyarko",
     "phoneNumber": "0244456497",
     "email": "Nyarko49Vincent@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "JgUxUtIhen",
     "remember": true,
     "status": "Verified"
   },
   {
     "id": 50,
     "firstname": "Lois",
     "lastname": "Nuamah",
     "phoneNumber": "0244456507",
     "email": "Nuamah50Lois@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "drRECdRHOv",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 51,
     "firstname": "Samaria",
     "lastname": "Obeng",
     "phoneNumber": "0244456517",
     "email": "Obeng51Samaria@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "ANYzAPclMj",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 52,
     "firstname": "Lois",
     "lastname": "Dankyi",
     "phoneNumber": "0244456527",
     "email": "Dankyi52Lois@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "PwQujoanmm",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 53,
     "firstname": "Sam",
     "lastname": "Osei",
     "phoneNumber": "0244456537",
     "email": "Osei53Sam@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "vdyatyDAjm",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 54,
     "firstname": "David",
     "lastname": "Obeng",
     "phoneNumber": "0244456547",
     "email": "Obeng54David@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "jSfKNCXQYS",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 55,
     "firstname": "Sam",
     "lastname": "Daniels",
     "phoneNumber": "0244456557",
     "email": "Daniels55Sam@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "WnuzOpkEkR",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 56,
     "firstname": "David",
     "lastname": "Agyeman",
     "phoneNumber": "0244456567",
     "email": "Agyeman56David@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "GJjVHlhCXt",
     "remember": true,
     "status": "Verified"
   },
   {
     "id": 57,
     "firstname": "Yaa",
     "lastname": "Agyeman",
     "phoneNumber": "0244456577",
     "email": "Agyeman57Yaa@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "jGJvptIMTP",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 58,
     "firstname": "Richeal",
     "lastname": "Ofosu",
     "phoneNumber": "0244456587",
     "email": "Ofosu58Richeal@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "stnOtdViyk",
     "remember": true,
     "status": "Verified"
   },
   {
     "id": 59,
     "firstname": "Alex",
     "lastname": "Dankyi",
     "phoneNumber": "0244456597",
     "email": "Dankyi59Alex@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "oRYNSRsjZI",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 60,
     "firstname": "Prince",
     "lastname": "Agyeman",
     "phoneNumber": "0244456607",
     "email": "Agyeman60Prince@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "vppgbsfZif",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 61,
     "firstname": "Israel",
     "lastname": "Nuamah",
     "phoneNumber": "0244456617",
     "email": "Nuamah61Israel@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "mBQliTNlVt",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 62,
     "firstname": "Joel",
     "lastname": "Ofosu",
     "phoneNumber": "0244456627",
     "email": "Ofosu62Joel@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "HgkINtEXMZ",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 63,
     "firstname": "Lois",
     "lastname": "Dankyi",
     "phoneNumber": "0244456637",
     "email": "Dankyi63Lois@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "PyajqZmnSb",
     "remember": true,
     "status": "Locked"
   },
   {
     "id": 64,
     "firstname": "Yaa",
     "lastname": "Dankyi",
     "phoneNumber": "0244456647",
     "email": "Dankyi64Yaa@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "xdZOIMXnaK",
     "remember": true,
     "status": "Verified"
   },
   {
     "id": 65,
     "firstname": "Alex",
     "lastname": "Nyarko",
     "phoneNumber": "0244456657",
     "email": "Nyarko65Alex@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "cVykjIcuAz",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 66,
     "firstname": "Lois",
     "lastname": "Badu",
     "phoneNumber": "0244456667",
     "email": "Badu66Lois@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "wScWiYawdr",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 67,
     "firstname": "Yaa",
     "lastname": "Vanderpuije",
     "phoneNumber": "0244456677",
     "email": "Vanderpuije67Yaa@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "qJthFWjUUI",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 68,
     "firstname": "Vincent",
     "lastname": "Badu",
     "phoneNumber": "0244456687",
     "email": "Badu68Vincent@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "aLynYvvPKW",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 69,
     "firstname": "Joel",
     "lastname": "Agyeman",
     "phoneNumber": "0244456697",
     "email": "Agyeman69Joel@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "iiwhIwljwT",
     "remember": true,
     "status": "Verified"
   },
   {
     "id": 70,
     "firstname": "Daniel",
     "lastname": "Bonsu",
     "phoneNumber": "0244456707",
     "email": "Bonsu70Daniel@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "xIQsyIkdQK",
     "remember": true,
     "status": "Verified"
   },
   {
     "id": 71,
     "firstname": "David",
     "lastname": "Agyeman",
     "phoneNumber": "0244456717",
     "email": "Agyeman71David@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "KtLGPSjElU",
     "remember": true,
     "status": "Verified"
   },
   {
     "id": 72,
     "firstname": "Joel",
     "lastname": "Tetteh",
     "phoneNumber": "0244456727",
     "email": "Tetteh72Joel@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "ECRpUkUhCR",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 73,
     "firstname": "Felix",
     "lastname": "Amorin",
     "phoneNumber": "0244456737",
     "email": "Amorin73Felix@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "hJsrogJMmi",
     "remember": true,
     "status": "Verified"
   },
   {
     "id": 74,
     "firstname": "Agatha",
     "lastname": "Vanderpuije",
     "phoneNumber": "0244456747",
     "email": "Vanderpuije74Agatha@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "jVKWffZJpF",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 75,
     "firstname": "Samaria",
     "lastname": "Nyarko",
     "phoneNumber": "0244456757",
     "email": "Nyarko75Samaria@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "WQnGTSWxcx",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 76,
     "firstname": "Joseph",
     "lastname": "Bonsu",
     "phoneNumber": "0244456767",
     "email": "Bonsu76Joseph@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "KcQxTZFEGg",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 77,
     "firstname": "Rita",
     "lastname": "Amorin",
     "phoneNumber": "0244456777",
     "email": "Amorin77Rita@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "BrytDeKkmO",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 78,
     "firstname": "Richeal",
     "lastname": "Badu",
     "phoneNumber": "0244456787",
     "email": "Badu78Richeal@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "xBWAGHEghS",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 79,
     "firstname": "Lois",
     "lastname": "Bonsu",
     "phoneNumber": "0244456797",
     "email": "Bonsu79Lois@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "RYEuetCsMn",
     "remember": true,
     "status": "Locked"
   },
   {
     "id": 80,
     "firstname": "Lois",
     "lastname": "Nyarko",
     "phoneNumber": "0244456807",
     "email": "Nyarko80Lois@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "iyzPBUMfmj",
     "remember": true,
     "status": "Verified"
   },
   {
     "id": 81,
     "firstname": "Prince",
     "lastname": "Gyamfi",
     "phoneNumber": "0244456817",
     "email": "Gyamfi81Prince@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "fWHgrMokCD",
     "remember": true,
     "status": "Locked"
   },
   {
     "id": 82,
     "firstname": "Joel",
     "lastname": "Agyeman",
     "phoneNumber": "0244456827",
     "email": "Agyeman82Joel@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "rsloFPmBYe",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 83,
     "firstname": "Yaa",
     "lastname": "Tetteh",
     "phoneNumber": "0244456837",
     "email": "Tetteh83Yaa@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "MqNBCstFch",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 84,
     "firstname": "David",
     "lastname": "Ofosu",
     "phoneNumber": "0244456847",
     "email": "Ofosu84David@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "PPLwmefGDr",
     "remember": true,
     "status": "Locked"
   },
   {
     "id": 85,
     "firstname": "Rita",
     "lastname": "Agyeman",
     "phoneNumber": "0244456857",
     "email": "Agyeman85Rita@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "CCnTLzUZWB",
     "remember":true,
     "status": "Blocked"
   },
   {
     "id": 86,
     "firstname": "Israel",
     "lastname": "Dankyi",
     "phoneNumber": "0244456867",
     "email": "Dankyi86Israel@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "KpXOamzrQR",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 87,
     "firstname": "Sefakor",
     "lastname": "Nuamah",
     "phoneNumber": "0244456877",
     "email": "Nuamah87Sefakor@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "ldLEpIKKjr",
     "remember": true,
     "status": "Verified"
   },
   {
     "id": 88,
     "firstname": "Rita",
     "lastname": "Bonsu",
     "phoneNumber": "0244456887",
     "email": "Bonsu88Rita@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "jTyIQsTCYt",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 89,
     "firstname": "Rita",
     "lastname": "Agyeman",
     "phoneNumber": "0244456897",
     "email": "Agyeman89Rita@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "sigxDGWtqa",
     "remember": true,
     "status": "Locked"
   },
   {
     "id": 90,
     "firstname": "Daniel",
     "lastname": "Bonsu",
     "phoneNumber": "0244456907",
     "email": "Bonsu90Daniel@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "BphtTqFDny",
     "remember": true,
     "status": "Verified"
   },
   {
     "id": 91,
     "firstname": "Vincent",
     "lastname": "Agyeman",
     "phoneNumber": "0244456917",
     "email": "Agyeman91Vincent@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "COLirUqZzx",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 92,
     "firstname": "Alex",
     "lastname": "Gyamfi",
     "phoneNumber": "0244456927",
     "email": "Gyamfi92Alex@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "WuBdPlsSzT",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 93,
     "firstname": "Joel",
     "lastname": "Nuamah",
     "phoneNumber": "0244456937",
     "email": "Nuamah93Joel@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "qpGgaNAUVL",
     "remember": true,
     "status": "Verified"
   },
   {
     "id": 94,
     "firstname": "Sam",
     "lastname": "Nyarko",
     "phoneNumber": "0244456947",
     "email": "Nyarko94Sam@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "kIXReFOTfj",
     "remember": true,
     "status": "Locked"
   },
   {
     "id": 95,
     "firstname": "Daniel",
     "lastname": "Obeng",
     "phoneNumber": "0244456957",
     "email": "Obeng95Daniel@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "HtrwedZkgf",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 96,
     "firstname": "Prince",
     "lastname": "Amorin",
     "phoneNumber": "0244456967",
     "email": "Amorin96Prince@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "UdrdDsBbdb",
     "remember": true,
     "status": "Verified"
   },
   {
     "id": 97,
     "firstname": "Israel",
     "lastname": "Daniels",
     "phoneNumber": "0244456977",
     "email": "Daniels97Israel@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "sDXhqJzNoJ",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 98,
  "firstname": "Israel",
     "lastname": "Agyeman",
     "phoneNumber": "0244456987",
     "email": "Agyeman98Israel@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "lRZfSlrHfv",
     "remember": true,
     "status": "Locked"
   },
   {
     "id": 99,
     "firstname": "Sefakor",
     "lastname": "Tetteh",
     "phoneNumber": "0244456997",
     "email": "Tetteh99Sefakor@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "IfCzElIysx",
     "remember": true,
     "status": "Locked"
   },
   {
     "id": 100,
     "firstname": "Prince",
     "lastname": "Vanderpuije",
     "phoneNumber": "02444561007",
     "email": "Vanderpuije100Prince@gmail.com",
     "role": "User",
     "createdBy": "Super Admin",
     "createdDate": "2023-10-26T11:08:25.756Z",
     "password": "cRvgAfgavB",
     "remember": true,
     "status": "Verified"
   }
 ]

}
