import { Injectable } from '@angular/core';
import { User } from '../interfaces/user';
import { FIUser } from './../interfaces/fiUser';

@Injectable({
  providedIn: 'root'
})
export class UserService {

  constructor() { }
 makers: User[] =
 [
   {
     "id": 1,
     "firstname": "David",
     "lastname": "Daniels",
     "phoneNumber": "024445617",
     "email": "Daniels1David@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "aFQcSzegeQ",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 2,
     "firstname": "Vincent",
     "lastname": "Ofosu",
     "phoneNumber": "024445627",
     "email": "Ofosu2Vincent@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "mFJYIAVnbI",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 3,
     "firstname": "Felix",
     "lastname": "Obeng",
     "phoneNumber": "024445637",
     "email": "Obeng3Felix@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "JIICKTzVOy",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 4,
     "firstname": "Sefakor",
     "lastname": "Dankyi",
     "phoneNumber": "024445647",
     "email": "Dankyi4Sefakor@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "cZLbxFMYpS",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 5,
     "firstname": "Richeal",
     "lastname": "Bonsu",
     "phoneNumber": "024445657",
     "email": "Bonsu5Richeal@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "OhSvGdEHAe",
     "remember": true,
     "status": "New"
   },
   {
     "id": 6,
     "firstname": "Vincent",
     "lastname": "Agyeman",
     "phoneNumber": "024445667",
     "email": "Agyeman6Vincent@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "BYjaKLXtWf",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 7,
     "firstname": "Sefakor",
     "lastname": "Amorin",
     "phoneNumber": "024445677",
     "email":"Amorin7Sefakor@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "HMBBpXiBhy",
     "remember": true,
     "status": "New"
   },
   {
     "id": 8,
     "firstname": "Yaa",
     "lastname": "Agyeman",
     "phoneNumber": "024445687",
     "email": "Agyeman8Yaa@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "zjGSIeFcRq",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 9,
     "firstname": "Daniel",
     "lastname": "Gyamfi",
     "phoneNumber": "024445697",
     "email": "Gyamfi9Daniel@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "RVOyldxIdZ",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 10,
     "firstname": "Daniel",
     "lastname": "Nuamah",
     "phoneNumber": "0244456107",
     "email": "Nuamah10Daniel@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "PCkvygQvao",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 11,
     "firstname": "Felix",
     "lastname": "Agyeman",
     "phoneNumber": "0244456117",
     "email": "Agyeman11Felix@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "OhWLBtkQww",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 12,
     "firstname": "David",
     "lastname": "Amorin",
     "phoneNumber": "0244456127",
     "email": "Amorin12David@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "fAoquCNJjW",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 13,
     "firstname": "Lois",
     "lastname": "Osei",
     "phoneNumber": "0244456137",
     "email": "Osei13Lois@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "YmmnvHpyNY",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 14,
     "firstname": "Felix",
     "lastname": "Gyamfi",
     "phoneNumber": "0244456147",
     "email": "Gyamfi14Felix@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "AvZOemyQsh",
     "remember": true,
     "status": "New"
   },
   {
     "id": 15,
     "firstname": "Alex",
     "lastname": "Tetteh",
     "phoneNumber": "0244456157",
     "email": "Tetteh15Alex@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "YflSZxtQWA",
     "remember": true,
     "status": "New"
   },
   {
     "id": 16,
     "firstname": "Agatha",
     "lastname": "Bonsu",
     "phoneNumber": "0244456167",
     "email": "Bonsu16Agatha@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "UOTLVYjJXC",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 17,
     "firstname": "Sam",
     "lastname": "Gyamfi",
     "phoneNumber": "0244456177",
     "email": "Gyamfi17Sam@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "ovmKnCnuwf",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 18,
     "firstname": "Vincent",
     "lastname": "Nuamah",
     "phoneNumber": "0244456187",
     "email": "Nuamah18Vincent@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "urAsnKGPDD",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 19,
     "firstname": "Emma",
     "lastname": "Dankyi",
     "phoneNumber": "0244456197",
     "email": "Dankyi19Emma@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "FJKXqiiQAy",
     "remember": true,
     "status": "New"
   },
   {
     "id": 20,
     "firstname": "Sefakor",
     "lastname": "Vanderpuije",
     "phoneNumber": "0244456207",
     "email": "Vanderpuije20Sefakor@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "XaIYVSYekg",
     "remember": true,
     "status": "New"
   },
   {
     "id": 21,
     "firstname": "Agatha",
     "lastname": "Nyarko",
     "phoneNumber": "0244456217",
     "email": "Nyarko21Agatha@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "huAlYwLwCq",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 22,
     "firstname": "Samaria",
     "lastname": "Daniels",
     "phoneNumber": "0244456227",
     "email": "Daniels22Samaria@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "hHuuoNDpKT",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 23,
     "firstname": "Sefakor",
     "lastname": "Daniels",
     "phoneNumber": "0244456237",
     "email": "Daniels23Sefakor@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "UzicAsAFut",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 24,
     "firstname": "Samaria",
     "lastname": "Peprah",
     "phoneNumber": "0244456247",
     "email": "Peprah24Samaria@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "GwHvRgNmdO",
     "remember": true,
     "status": "New"
   },
   {
     "id": 25,
     "firstname": "Lois",
     "lastname": "Bonsu",
     "phoneNumber": "0244456257",
     "email": "Bonsu25Lois@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "uetncYNvAl",
     "remember": true,
     "status": "New"
   },
   {
     "id": 26,
     "firstname": "Joseph",
     "lastname": "Agyeman",
     "phoneNumber": "0244456267",
     "email": "Agyeman26Joseph@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "veIwUsOluE",
     "remember": true,
     "status": "Blocked"
   },
   {
     "id": 27,
     "firstname": "Joel",
     "lastname": "Gyamfi",
     "phoneNumber": "0244456277",
     "email": "Gyamfi27Joel@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "mCNEiPPsld",
     "remember": true,
     "status": "New"
   },
   {
     "id": 28,
     "firstname": "Rita",
     "lastname": "Agyeman",
     "phoneNumber": "0244456287",
     "email": "Agyeman28Rita@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "vqVJdduoyu",
     "remember": true,
     "status": "New"
   },
   {
     "id": 29,
     "firstname": "Daniel",
     "lastname": "Bonsu",
     "phoneNumber": "0244456297",
     "email": "Bonsu29Daniel@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "zgVPMOdmBb",
     "remember": true,
     "status": "Active"
   },
   {
     "id": 30,
     "firstname": "Yaa",
     "lastname": "Amorin",
     "phoneNumber": "0244456307",
     "email": "Amorin30Yaa@gmail.com",
     "role": "Maker",
     "createdBy": "SCF Admin",
     "createdDate": "2023-10-31T18:26:29.316Z",
     "password": "UHMxlZiabs",
     "remember": true,
     "status": "Active"
   }
 ]

checkers: User[] = [
  {
    "id": 1,
    "firstname": "Richeal",
    "lastname": "Osei",
    "phoneNumber": "024355617",
    "email": "Osei1Richeal@gmail.com",
    "role": "Checker",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T18:29:25.857Z",
    "password": "MVOaulSgcj",
    "remember": true,
    "status": "Active"
  },
  {
    "id": 2,
    "firstname": "Joseph",
    "lastname": "Osei",
    "phoneNumber": "024355627",
    "email": "Osei2Joseph@gmail.com",
    "role": "Checker",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T18:29:25.857Z",
    "password": "yrwjOxPQcr",
    "remember": true,
    "status": "New"
  },
  {
    "id": 3,
    "firstname": "Joseph",
    "lastname": "Peprah",
    "phoneNumber": "024355637",
    "email": "Peprah3Joseph@gmail.com",
    "role": "Checker",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T18:29:25.857Z",
    "password": "SRomfgnTLa",
    "remember": true,
    "status": "New"
  },
  {
    "id": 4,
    "firstname": "Vincent",
    "lastname": "Peprah",
    "phoneNumber": "024355647",
    "email": "Peprah4Vincent@gmail.com",
    "role": "Checker",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T18:29:25.857Z",
    "password": "XfxPkxJuFe",
    "remember": true,
    "status": "Blocked"
  },
  {
    "id": 5,
    "firstname": "David",
    "lastname": "Peprah",
    "phoneNumber": "024355657",
    "email": "Peprah5David@gmail.com",
    "role": "Checker",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T18:29:25.857Z",
    "password": "pMWFlMOVpt",
    "remember": true,
    "status": "Active"
  },
  {
    "id": 6,
    "firstname": "Sefakor",
    "lastname": "Bonsu",
    "phoneNumber": "024355667",
    "email": "Bonsu6Sefakor@gmail.com",
    "role": "Checker",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T18:29:25.857Z",
    "password": "JPgEzvvKbu",
    "remember": true,
    "status": "Blocked"
  },
  {
    "id": 7,
    "firstname": "Alex",
    "lastname": "Agyeman",
    "phoneNumber": "024355677",
    "email": "Agyeman7Alex@gmail.com",
    "role": "Checker",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T18:29:25.857Z",
    "password": "mJhuRHVaNi",
    "remember": true,
    "status": "Active"
  },
  {
    "id": 8,
    "firstname": "Prince",
    "lastname": "Ofosu",
    "phoneNumber": "024355687",
    "email": "Ofosu8Prince@gmail.com",
    "role": "Checker",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T18:29:25.857Z",
    "password": "miPCtpgXwA",
    "remember": true,
    "status": "Blocked"
  },
  {
    "id": 9,
    "firstname": "David",
    "lastname": "Osei",
    "phoneNumber": "024355697",
    "email": "Osei9David@gmail.com",
    "role": "Checker",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T18:29:25.857Z",
    "password": "jayFkXEHZg",
    "remember": true,
    "status": "Blocked"
  },
  {
    "id": 10,
    "firstname": "Felix",
    "lastname": "Gyamfi",
    "phoneNumber": "0243556107",
    "email": "Gyamfi10Felix@gmail.com",
    "role": "Checker",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T18:29:25.857Z",
    "password": "nAEARvteiz",
    "remember": true,
    "status": "New"
  },
  {
    "id": 11,
    "firstname": "Agatha",
    "lastname": "Osei",
    "phoneNumber": "0243556117",
    "email": "Osei11Agatha@gmail.com",
    "role": "Checker",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T18:29:25.857Z",
    "password": "oqgPTjsFTW",
    "remember": true,
    "status": "New"
  },
  {
    "id": 12,
    "firstname": "Felix",
    "lastname": "Daniels",
    "phoneNumber": "0243556127",
    "email": "Daniels12Felix@gmail.com",
    "role": "Checker",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T18:29:25.857Z",
    "password": "uVtYpxoMnC",
    "remember": true,
    "status": "Blocked"
  },
  {
    "id": 13,
    "firstname": "Sefakor",
    "lastname": "Dankyi",
    "phoneNumber": "0243556137",
    "email": "Dankyi13Sefakor@gmail.com",
    "role": "Checker",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T18:29:25.857Z",
    "password": "haTFtIvLpH",
    "remember": true,
    "status": "New"
  },
  {
    "id": 14,
    "firstname": "Daniel",
    "lastname": "Peprah",
    "phoneNumber": "0243556147",
    "email": "Peprah14Daniel@gmail.com",
    "role": "Checker",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T18:29:25.857Z",
    "password": "AWXzZegUpW",
    "remember": true,
    "status": "Active"
  },
  {
    "id": 15,
    "firstname": "Samaria",
    "lastname": "Badu",
    "phoneNumber": "0243556157",
    "email": "Badu15Samaria@gmail.com",
    "role": "Checker",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T18:29:25.857Z",
    "password": "pjNzTmurAj",
    "remember": true,
    "status": "Active"
  }
]

banks: FIUser[] =
[
  {
    "id": 1,
    "fi_name": "National Bank",
    "fi_shortName": "NB1",
    "fi_code": "FI014831",
    "fi_type": "Bank",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.792Z",
    "password": "ytiWXdWhwr",
    "status": "Deleted"
  },
  {
    "id": 2,
    "fi_name": "United Bank",
    "fi_shortName": "UB2",
    "fi_code": "FI014832",
    "fi_type": "Bank",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.792Z",
    "password": "gfkWshxcCV",
    "status": "Active"
  },
  {
    "id": 3,
    "fi_name": "Commercial Microfinance",
    "fi_shortName": "CM3",
    "fi_code": "FI014833",
    "fi_type": "Non-Bank Financial",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.792Z",
    "password": "CEJJlXdfoT",
    "status": "Deleted"
  },
  {
    "id": 4,
    "fi_name": "Agricultural Savings & Loans",
    "fi_shortName": "AS4",
    "fi_code": "FI014834",
    "fi_type": "Non-Bank Financial",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.792Z",
    "password": "msMEzAafJo",
    "status": "Deactivated"
  },
  {
    "id": 5,
    "fi_name": "National Bank",
    "fi_shortName": "NB5",
    "fi_code": "FI014835",
    "fi_type": "Bank",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.792Z",
    "password": "TbKFkTQynV",
    "status": "Active"
  },
  {
    "id": 6,
    "fi_name": "Agricultural Bank",
    "fi_shortName": "AB6",
    "fi_code": "FI014836",
    "fi_type": "Bank",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.792Z",
    "password": "LcxDOpzkEo",
    "status": "Active"
  },
  {
    "id": 7,
    "fi_name": "Development Bank",
    "fi_shortName": "DB7",
    "fi_code": "FI014837",
    "fi_type": "Bank",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.792Z",
    "password": "IfauHIUDYx",
    "status": "Deactivated"
  },
  {
    "id": 8,
    "fi_name": "National Bank",
    "fi_shortName": "NB8",
    "fi_code": "FI014838",
    "fi_type": "Bank",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.792Z",
    "password": "oULOQQeMmt",
    "status": "Active"
  },
  {
    "id": 9,
    "fi_name": "Commercial Bank",
    "fi_shortName": "CB9",
    "fi_code": "FI014839",
    "fi_type": "Bank",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.792Z",
    "password": "DXgtGvHcME",
    "status": "Deactivated"
  },
  {
    "id": 10,
    "fi_name": "United Bank",
    "fi_shortName": "UB10",
    "fi_code": "FI0148310",
    "fi_type": "Bank",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.792Z",
    "password": "YGByMXvKZC",
    "status": "Deactivated"
  },
  {
    "id": 11,
    "fi_name": "National Bank",
    "fi_shortName": "NB11",
    "fi_code": "FI0148311",
    "fi_type": "Bank",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.793Z",
    "password": "TjVQqHoixU",
    "status": "Deleted"
  },
  {
    "id": 12,
    "fi_name": "Capital Microfinance",
    "fi_shortName": "CM12",
    "fi_code": "FI0148312",
    "fi_type": "Non-Bank Financial",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.793Z",
    "password": "yMClhRDLgP",
    "status": "Active"
  },
  {
    "id": 13,
    "fi_name": "Commercial Savings & Loans",
    "fi_shortName": "CS13",
    "fi_code": "FI0148313",
    "fi_type": "Non-Bank Financial",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.793Z",
    "password": "NaKoWHNCjh",
    "status": "Active"
  },
  {
    "id": 14,
    "fi_name": "Agricultural Bank",
    "fi_shortName": "AB14",
    "fi_code": "FI0148314",
    "fi_type": "Bank",
   "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.793Z",
    "password": "FunJLyPEcE",
    "status": "Active"
  },
  {
    "id": 15,
    "fi_name": "United Microfinance",
    "fi_shortName": "UM15",
    "fi_code": "FI0148315",
    "fi_type": "Non-Bank Financial",
    "role": "FI",
    "createdBy": "SCF Admin",
    "createdDate": "2023-10-31T19:02:33.793Z",
    "password": "TNEJygQTPC",
    "status": "Active"
  }
]


}
